on: [push, pull_request]

name: CI
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: v1-pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements-*.txt') }}
          restore-keys: |
            v1-pip-${{ runner.os }}-${{ matrix.python-version }}
            v1-pip-${{ runner.os }}
            v1-pip-
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Test
        run: mreg-cli --playback testsuite-result.json
